const successCode = 200
const badRequestCode = 400
const errorCode = 500
const successfulCreationCode = 201
const resourceConflictCode = 409
const invalidAuthenticationCode = 401
const dataNotFoundCode = 404
const tokenRequiredCode=403
const saltRound = 10
const loginSuccess = "logged in successfully"
const invalidFile = "invalid file path"
const successfulAccountCreation = "account created successfully"
const successfulTaskCreation = "task created successfully"
const successfulTaskUpdation = "task updated successfully"
const successfulTaskDeletion = "task deleted successfully"
const userNameResourceConflict = "user name already exists"
const idConflict = "id already exists"
const invalidUserName = "user name does not exists"
const invalidPassword = "invalid password"
const invalidToken = "invalid token"
const invalidData = "invalid data"
const tokenRequired = "A token is required for authentication"
const taskNotFound ="task does not exists"
const taskCreationRequired = "User's task list is empty"
const matchNotFound = "there are no tasks to display"
module.exports = {successfulTaskCreation,errorCode,successfulTaskUpdation,successfulTaskDeletion, successCode, badRequestCode, successfulCreationCode, resourceConflictCode, invalidAuthenticationCode, loginSuccess, invalidFile, successfulAccountCreation, userNameResourceConflict, invalidPassword,dataNotFoundCode,invalidUserName,saltRound,tokenRequiredCode,invalidToken,tokenRequired,idConflict,invalidData,taskNotFound,taskCreationRequired,matchNotFound}
